# Frappe hooks.py configuration for brand theming.
#
# Add these to your Frappe custom app's hooks.py (e.g. munimco_brand/hooks.py).
# The CSS files are generated by: python -m brand.generate_css
#
# Copy the generated files to:
#   munimco_brand/public/css/desk.css
#   munimco_brand/public/css/portal.css
#
# Copy head_fonts.html content into Website Theme → Custom <head> HTML.

app_include_css = "/assets/munimco_brand/css/desk.css"
web_include_css = "/assets/munimco_brand/css/portal.css"

# Upload logo files from brand/assets/ to:
#   Navbar Settings → App Logo
#   Website Settings → Favicon (use the M icon)
#   Login Page → Logo
